version: "3"
services:
  postgresql:
    image: postgres
    restart: always
    container_name: local-postgres
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=users"
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - 15432:5432

  #usersservice:
  #  image: usersservice
  #  build:
  #    context: .
  #    dockerfile: UsersService/Dockerfile